/**
 * Dizionario unico allineato al catalogo esami del simulatore (`SimulatorClient`).
 * Usato da: simulatore, creazione caso, merge AI, admin valori esami.
 */
export type ExamClinicalMeta = {
  price: number;
  urgencyTiming: string;
  routineTiming: string;
  routineMinutes: number;
  normalFinding: string;
};

export const EXAM_DEFAULT_VALUES: Record<string, ExamClinicalMeta> = {
  lattati: { price: 5, urgencyTiming: "15 min", routineTiming: "1h", routineMinutes: 60, normalFinding: "0.5 – 2.2 mmol/L" },
  ammoniemia: { price: 8.5, urgencyTiming: "45 min", routineTiming: "2h", routineMinutes: 120, normalFinding: "15 – 45 µg/dL" },
  "amilasi-lipasi": { price: 7, urgencyTiming: "1h", routineTiming: "4h", routineMinutes: 240, normalFinding: "Amilasi <100 U/L; Lipasi <60 U/L" },
  "assetto-lipidico": { price: 12, urgencyTiming: "n.p.", routineTiming: "12h", routineMinutes: 720, normalFinding: "Tot <200; LDL <130; HDL >50 mg/dL" },
  bilirubina: { price: 3.5, urgencyTiming: "1h", routineTiming: "4h", routineMinutes: 240, normalFinding: "Totale 0.3 – 1.2 mg/dL" },
  "creat-urea-gfr": { price: 4.5, urgencyTiming: "1h", routineTiming: "4h", routineMinutes: 240, normalFinding: "Creatinina 0.6-1.2 mg/dL; GFR >90" },
  elettroliti: { price: 6.5, urgencyTiming: "1h", routineTiming: "4h", routineMinutes: 240, normalFinding: "Na 135-145; K 3.5-5.0 mEq/L" },
  protidogramma: { price: 8, urgencyTiming: "n.p.", routineTiming: "24-48h", routineMinutes: 1440, normalFinding: "Albumina 55-65%" },
  hba1c: { price: 10.5, urgencyTiming: "n.p.", routineTiming: "24h", routineMinutes: 1440, normalFinding: "< 39 mmol/mol (o < 5.7%)" },
  glicemia: { price: 2.1, urgencyTiming: "15 min", routineTiming: "4h", routineMinutes: 240, normalFinding: "70 – 100 mg/dL" },
  "enzimi-epatici": { price: 10, urgencyTiming: "1h", routineTiming: "4h", routineMinutes: 240, normalFinding: "AST/ALT <40 U/L; GGT <50 U/L" },
  ldh: { price: 3, urgencyTiming: "1h", routineTiming: "4h", routineMinutes: 240, normalFinding: "135 – 225 U/L" },
  mioglobina: { price: 15, urgencyTiming: "45 min", routineTiming: "2h", routineMinutes: 120, normalFinding: "< 80 ng/mL" },
  "nt-probnp": { price: 35, urgencyTiming: "1h", routineTiming: "4h", routineMinutes: 240, normalFinding: "< 125 pg/mL" },
  "pcr-pct": { price: 28, urgencyTiming: "1h", routineTiming: "4h", routineMinutes: 240, normalFinding: "PCR <0.5 mg/dL; PCT <0.05 ng/mL" },
  "troponina-hs": { price: 18, urgencyTiming: "45 min", routineTiming: "2h", routineMinutes: 120, normalFinding: "< 14 ng/L" },
  uricemia: { price: 3, urgencyTiming: "1h", routineTiming: "4h", routineMinutes: 240, normalFinding: "2.5 – 7.0 mg/dL" },
  vitamine: { price: 45, urgencyTiming: "n.p.", routineTiming: "3-5 gg", routineMinutes: 4320, normalFinding: "Vit D 30-100 ng/mL" },
  antitrombina: { price: 12, urgencyTiming: "2h", routineTiming: "12h", routineMinutes: 720, normalFinding: "80% – 120%" },
  ddimero: { price: 16, urgencyTiming: "1h", routineTiming: "4h", routineMinutes: 240, normalFinding: "< 500 ng/mL" },
  emocromo: { price: 4.8, urgencyTiming: "20 min", routineTiming: "4h", routineMinutes: 240, normalFinding: "Hb 13-17 (M) / 12-15 (F) g/dL" },
  "assetto-marziale": { price: 14, urgencyTiming: "n.p.", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Ferritina 30 – 300 ng/mL" },
  fibrinogeno: { price: 6.5, urgencyTiming: "1h", routineTiming: "4h", routineMinutes: 240, normalFinding: "200 – 400 mg/dL" },
  "gruppo-rh": { price: 18, urgencyTiming: "30 min", routineTiming: "4h", routineMinutes: 240, normalFinding: "Esempio: 0 Positivo" },
  "pt-ptt-inr": { price: 8.5, urgencyTiming: "45 min", routineTiming: "4h", routineMinutes: 240, normalFinding: "INR 0.8 – 1.2" },
  reticolociti: { price: 5, urgencyTiming: "2h", routineTiming: "12h", routineMinutes: 720, normalFinding: "0.5% – 2.0%" },
  ves: { price: 3.5, urgencyTiming: "n.p.", routineTiming: "2h", routineMinutes: 120, normalFinding: "<15 mm/h (M) / <20 mm/h (F)" },
  "acth-cortisolo": { price: 32, urgencyTiming: "n.p.", routineTiming: "3 gg", routineMinutes: 4320, normalFinding: "Cortisolo (8:00): 5 – 25 µg/dL" },
  "aldosterone-renina": { price: 48, urgencyTiming: "n.p.", routineTiming: "7 gg", routineMinutes: 10080, normalFinding: "Rapporto ARR < 20-30" },
  "beta-hcg": { price: 15, urgencyTiming: "2h", routineTiming: "6h", routineMinutes: 360, normalFinding: "< 5 mUI/mL (Negativo)" },
  catecolamine: { price: 45, urgencyTiming: "n.p.", routineTiming: "10 gg", routineMinutes: 14400, normalFinding: "Adrenalina ur. < 20 µg/24h" },
  "fsh-lh-prl": { price: 28, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "Prolattina 5 – 20 ng/mL" },
  "insulina-cpep": { price: 22, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "Insulina 3 – 25 µUI/mL" },
  "gh-igf1": { price: 35, urgencyTiming: "n.p.", routineTiming: "5 gg", routineMinutes: 7200, normalFinding: "GH < 5 ng/mL" },
  tiroide: { price: 22, urgencyTiming: "n.p.", routineTiming: "24h", routineMinutes: 1440, normalFinding: "TSH 0.4 – 4.0 µUI/mL" },
  pth: { price: 18, urgencyTiming: "n.p.", routineTiming: "24h", routineMinutes: 1440, normalFinding: "10 – 65 pg/mL" },
  "ormoni-sessuali": { price: 38, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "Variabile per sesso/ciclo" },
  "hiv-hcv-hbv": { price: 35, urgencyTiming: "4h", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Assente (Negativo)" },
  anca: { price: 32, urgencyTiming: "n.p.", routineTiming: "5-7 gg", routineMinutes: 7200, normalFinding: "Negativo" },
  "anti-ccp": { price: 18, urgencyTiming: "n.p.", routineTiming: "5-7 gg", routineMinutes: 7200, normalFinding: "< 20 U/mL (Negativo)" },
  "anti-dna": { price: 15, urgencyTiming: "n.p.", routineTiming: "5-7 gg", routineMinutes: 7200, normalFinding: "Negativo" },
  "ana-ena": { price: 45, urgencyTiming: "n.p.", routineTiming: "5-7 gg", routineMinutes: 7200, normalFinding: "Negativo / Titolo < 1:80" },
  "c3-c4": { price: 14, urgencyTiming: "n.p.", routineTiming: "24h", routineMinutes: 1440, normalFinding: "C3 90-180; C4 10-40 mg/dL" },
  fr: { price: 8, urgencyTiming: "n.p.", routineTiming: "24h", routineMinutes: 1440, normalFinding: "< 14 UI/mL" },
  immunoglobuline: { price: 28, urgencyTiming: "n.p.", routineTiming: "24h", routineMinutes: 1440, normalFinding: "IgG 700 – 1600 mg/dL" },
  torch: { price: 55, urgencyTiming: "n.p.", routineTiming: "3 gg", routineMinutes: 4320, normalFinding: "Assenza di IgM specifiche" },
  quantiferon: { price: 60, urgencyTiming: "n.p.", routineTiming: "4 gg", routineMinutes: 5760, normalFinding: "Negativo" },
  sifilide: { price: 12, urgencyTiming: "n.p.", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Negativo / Non reattivo" },
  coprocultura: { price: 25, urgencyTiming: "n.p.", routineTiming: "3 gg", routineMinutes: 4320, normalFinding: "Negativo" },
  emocolture: { price: 45, urgencyTiming: "24h", routineTiming: "5 gg", routineMinutes: 7200, normalFinding: "Negativo" },
  "urine-sed": { price: 6, urgencyTiming: "1h", routineTiming: "4h", routineMinutes: 240, normalFinding: "pH 6; Nitriti/Glucosio assenti" },
  cdiff: { price: 30, urgencyTiming: "4h", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Negativo" },
  "tox-screen": { price: 40, urgencyTiming: "2h", routineTiming: "12h", routineMinutes: 720, normalFinding: "Negativo" },
  tamponi: { price: 18, urgencyTiming: "n.p.", routineTiming: "48-72h", routineMinutes: 2880, normalFinding: "Flora saprofita normale" },
  urinocoltura: { price: 20, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "< 10^5 CFU/mL" },
  afp: { price: 15, urgencyTiming: "n.p.", routineTiming: "24h", routineMinutes: 1440, normalFinding: "< 10 ng/mL" },
  "beta-hcg-onco": { price: 15, urgencyTiming: "n.p.", routineTiming: "24h", routineMinutes: 1440, normalFinding: "< 5 mUI/mL" },
  "ca-markers": { price: 45, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "< 35 U/mL" },
  cea: { price: 15, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "< 3.0 ng/mL (non fumatori)" },
  calcitonina: { price: 20, urgencyTiming: "n.p.", routineTiming: "3 gg", routineMinutes: 4320, normalFinding: "< 10 pg/mL" },
  nse: { price: 20, urgencyTiming: "n.p.", routineTiming: "3 gg", routineMinutes: 4320, normalFinding: "< 12 ng/mL" },
  psa: { price: 18, urgencyTiming: "n.p.", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Totale < 4.0 ng/mL" },
  ecocolordoppler: { price: 65, urgencyTiming: "Immediato", routineTiming: "n.p.", routineMinutes: 35, normalFinding: "Vasi pervi, flusso regolare" },
  ecografia: { price: 55, urgencyTiming: "30 min", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Organi nei limiti per morfologia" },
  fast: { price: 40, urgencyTiming: "5 min", routineTiming: "n.p.", routineMinutes: 15, normalFinding: "Assenza di versamento libero" },
  mammografia: { price: 62, urgencyTiming: "n.p.", routineTiming: "3 gg", routineMinutes: 4320, normalFinding: "Assenza di lesioni sospette" },
  moc: { price: 52, urgencyTiming: "n.p.", routineTiming: "2 gg", routineMinutes: 2880, normalFinding: "T-score > -1.0" },
  "rx-addome": { price: 25, urgencyTiming: "30 min", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Assenza di aria libera/livelli" },
  "rx-ossa": { price: 30, urgencyTiming: "30 min", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Assenza di fratture recenti" },
  "rx-colonna": { price: 35, urgencyTiming: "30 min", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Rachide in asse" },
  "rx-torace": { price: 25, urgencyTiming: "30 min", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Parenchima polmonare libero" },
  angio: { price: 350, urgencyTiming: "2h", routineTiming: "48h", routineMinutes: 2880, normalFinding: "Arterie di calibro regolare" },
  "colangio-rm": { price: 250, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "Vie biliari non dilatate" },
  "pet-tc": { price: 950, urgencyTiming: "n.p.", routineTiming: "5 gg", routineMinutes: 7200, normalFinding: "Assenza di iperaccumuli patologici" },
  rm: { price: 220, urgencyTiming: "2h", routineTiming: "48h", routineMinutes: 2880, normalFinding: "Segnale parenchimale regolare" },
  "rm-prostata": { price: 280, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "PIRADS 1 o 2" },
  scintigrafia: { price: 250, urgencyTiming: "n.p.", routineTiming: "3 gg", routineMinutes: 4320, normalFinding: "Captazione omogenea" },
  tc: { price: 120, urgencyTiming: "1h", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Assenza aree alterata densità" },
  "uro-tc": { price: 180, urgencyTiming: "1h", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Regolare escrezione del mdc" },
  audiometria: { price: 15, urgencyTiming: "30 min", routineTiming: "n.p.", routineMinutes: 30, normalFinding: "Udito nei limiti di norma" },
  coronarografia: { price: 1800, urgencyTiming: "Real-time", routineTiming: "n.p.", routineMinutes: 120, normalFinding: "Albero coronarico indenne" },
  ecocardio: { price: 75, urgencyTiming: "1h", routineTiming: "24h", routineMinutes: 1440, normalFinding: "EF > 55%; valvole competenti" },
  ecg: { price: 15, urgencyTiming: "10 min", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Ritmo sinusale, no aritmie" },
  emg: { price: 70, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "Conduzione nervosa normale" },
  ega: { price: 10, urgencyTiming: "5-10 min", routineTiming: "n.p.", routineMinutes: 10, normalFinding: "pH 7.4; pO2 >80; pCO2 40 mmHg" },
  abpm: { price: 45, urgencyTiming: "24h", routineTiming: "n.p.", routineMinutes: 1440, normalFinding: "Media pressoria < 130/80" },
  spirometria: { price: 25, urgencyTiming: "30 min", routineTiming: "n.p.", routineMinutes: 30, normalFinding: "Rapporto Tiffeneau > 70%" },
  broncoscopia: { price: 280, urgencyTiming: "1h", routineTiming: "7 gg", routineMinutes: 10080, normalFinding: "Mucose bronchiali indenni" },
  cistoscopia: { price: 160, urgencyTiming: "1h", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Pareti vescicali regolari" },
  colonscopia: { price: 180, urgencyTiming: "1h", routineTiming: "7 gg", routineMinutes: 10080, normalFinding: "Mucosa del colon integra" },
  egds: { price: 140, urgencyTiming: "1h", routineTiming: "7 gg", routineMinutes: 10080, normalFinding: "Esofago e stomaco regolari" },
  liquidi: { price: 60, urgencyTiming: "2h", routineTiming: "5 gg", routineMinutes: 7200, normalFinding: "Assenza di atipie e batteri" },
  "pap-test": { price: 20, urgencyTiming: "n.p.", routineTiming: "15 gg", routineMinutes: 21600, normalFinding: "Negativo per cellule maligne" },
  // Esami nel catalogo RAW senza meta legacy — allineati a costi/tempi grezzi del catalogo
  eeg: { price: 90, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "Tracciato nei limiti per età, attività di base regolare" },
  fundus: { price: 60, urgencyTiming: "n.p.", routineTiming: "24h", routineMinutes: 1440, normalFinding: "Papilla e fondo oculare nei limiti" },
  oct: { price: 95, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "Strati retinici nei limiti" },
  polisonnografia: { price: 180, urgencyTiming: "1 notte", routineTiming: "7 gg", routineMinutes: 10080, normalFinding: "AHInel limite; saturazione notturna >90%" },
  "pot-evocati": { price: 120, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "Latenze e morfologia nei limiti" },
  "6mwt": { price: 35, urgencyTiming: "30 min", routineTiming: "n.p.", routineMinutes: 30, normalFinding: "Distanza e saturazione coerenti con età" },
  fna: { price: 120, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "Citologia: materiale adeguato, senza atipie significative" },
  biopsia: { price: 180, urgencyTiming: "n.p.", routineTiming: "7 gg", routineMinutes: 10080, normalFinding: "Istologia: tessuto rappresentativo, quadro non specifico" },
  laringoscopia: { price: 95, urgencyTiming: "n.p.", routineTiming: "48h", routineMinutes: 2880, normalFinding: "Strutture laringee mobili, senza lesioni evidenti" },
};
